---

- name: load condifguration
  become: yes
  template:
    src: "config_file.conf"
    dest: "{{ syslog.config.path }}/{{ syslog.config.file }}"
  tags: configure

- name: restart syslog
  become: yes
  systemd:
    name: syslogd
    state: "{{ syslog.state }}"
  tags: configure
