---

- name: ensure rsyslog is install
  become: yes
  package:
    name: rsyslog
    state: present
  register: rsyslog
  tags: install

- name: load condifguration
  become: yes
  template:
    src: "config_file.conf"
    dest: "{{ rsyslog.config.path }}/{{ rsyslog.config.file }}"
  tags: configure

- name: enable service
  become: yes
  systemd:
    name: rsyslog
    enabled: "{{ rsyslog.enabled }}"
  when: rsyslog.changed
  tags: configure

- name: load logrotate configuration
  template:
    src: "logrotate"
    dest: "/etc/logrotate.d/{{ rsyslog.logrotate.file }}"
  tags: configure

- name: restart rsyslog
  become: yes
  systemd:
    name: rsyslog
    state: "{{ rsyslog.state }}"
  tags: configure
