--- # system packages install

- name: ensure tools and programs are {{ package_state }}
  become: yes
  package:
    name: "{{ item }}"
    state: "{{ package_state }}"
  with_items: "{{ packages }}" 
  tags: install
